"""create initial tables

Revision ID: 3535470b9b78
Revises: 
Create Date: 2026-06-28 12:41:33.228361
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3535470b9b78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_type', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('daily_ohlcv',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_index('idx_ohlcv_symbol', 'daily_ohlcv', ['symbol'], unique=False)
    op.create_table('refresh_log',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_date_fetched', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('screen_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('screener_type', sa.String(length=10), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('smi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('stoch_k', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('stoch_d', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('crossover_type', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['tickers.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_screen_run', 'screen_results', ['run_date', 'screener_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_screen_run', table_name='screen_results')
    op.drop_table('screen_results')
    op.drop_table('refresh_log')
    op.drop_index('idx_ohlcv_symbol', table_name='daily_ohlcv')
    op.drop_table('daily_ohlcv')
    op.drop_table('tickers')
    # ### end Alembic commands ###
